version: 1.0
app:
  instances:
  
    min: 1
    max: 2
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
  variables:
    - name: discoveryEndpoint
      value: "https://jacobwdv-09262024.verify.ibm.com/oidc/endpoint/default/.well-known/openid-configuration"
    - name: clientId
      value: "18dc5a06-3a8c-4338-8559-452b54e14866"
  version: "717f33ef-49d4-4eb4-90be-a63c97868b91"
  java: 17
