version: 1.0
app:
  instances:
    min: 1
    max: 2
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
  variables:
    - name: discoveryEndpoint
      value: "https://jacobwdv-09302024.verify.ibm.com/oidc/endpoint/default/.well-known/openid-configuration"
    - name: clientId
      value: "0dbe576e-8e5f-419f-a9a4-f79504daa11b"
  version: "f1a625f5-7c07-4c84-9e0e-a37988674b0a"
  java: 17
