version: 1.1
app:
  endpoints: public
  instances:
    min: 1
    max: 2
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
  variables:
    - name: discoveryEndpoint
      value: "https://jacobwdv-11182024.verify.ibm.com/oidc/endpoint/default/.well-known/openid-configuration"
    - name: clientId
      value: "28c4afe5-2923-474b-b2e9-a192c01a5bdd"
  version: "c19165e8-4680-4931-9539-e907b6767c97"
  java: 17
